export const commonActions = {
  SET_SHOW_CHANGE_PASSWORD_MODAL: 'SHOW_CHANGE_PASSWORD_MODAL',
  SET_NOTIFICATION: 'SET_NOTIFICATION',
  SET_SHOW_NOTIFICATION: 'SET_SHOW_NOTIFICATION',
  SET_ETHERERUM_CONNECTION_ALERT: 'SET_ETHERERUM_CONNECTION_ALERT',
  SET_SHOW_OVERLAY_LOADING: 'SET_SHOW_OVERLAY_LOADING',
}

export const authActions = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  RESET_ERROR: 'RESET_ERROR',
}

export const productsActions = {
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  FETCH_PRODUCT_DETAILS: 'FETCH_PRODUCT_DETAILS',
}
