export const authGetters = {
  IS_AUTHENTICATED: 'IS_AUTHENTICATED',
  GET_CURRENT_USER: 'GET_CURRENT_USER',
  GET_ERROR_MSG: 'GET_ERROR_MSG',
}

export const productsGetters = {
  GET_TOTAL_PRODUCTS: 'GET_TOTAL_PRODUCTS',
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  GET_SELECTED_PRODUCT: 'GET_SELECTED_PRODUCT',
  GET_LATEST_PAGE: 'GET_LATEST_PAGE',
}

export const txsGetters = {
  GET_TOTAL_TRANSACTIONS: 'GET_TOTAL_TRANSACTIONS',
  GET_ALL_TRANSACTIONS: 'GET_ALL_TRANSACTIONS',
  GET_TOTAL_REVENUES: 'GET_TOTAL_REVENUES',
  GET_SELECTED_TRANSACTION: 'GET_SELECTED_TRANSACTION',
}
