export const authMutations = {
  SET_AUTH: 'SET_AUTH',
  SET_USER: 'SET_USER',
  PURGE_AUTH: 'PURGE_AUTH',
  SET_ERROR: 'SET_ERROR',
  SET_SUCCESS: 'SET_SUCCESS',
}

export const productsMutations = {
  SET_TOTAL_PRODUCTS: 'SET_TOTAL_PRODUCTS',
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_SUCCESS: 'SET_TOKEN_SUCCESS',
  SET_ERROR: 'SET_TOKEN_ERROR',
  RESET_STATE: 'RESET_TOKEN_STATE',
}
