export const commonMutations = {
  SET_SHOW_CHANGE_PASSWORD_MODAL: 'SET_SHOW_CHANGE_PASSWORD_MODAL',
  SET_NOTIFICATION: 'SET_NOTIFICATION',
  SET_SHOW_NOTIFICATION: 'SET_SHOW_NOTIFICATION',
  SET_ETHERERUM_CONNECTION_ALERT: 'SET_ETHERERUM_CONNECTION_ALERT',
  SET_SHOW_OVERLAY_LOADING: 'SET_SHOW_OVERLAY_LOADING',
}

export const authMutations = {
  SET_AUTH: 'SET_AUTH',
  SET_USER: 'SET_USER',
  PURGE_AUTH: 'PURGE_AUTH',
  SET_ERROR: 'SET_ERROR',
  SET_SUCCESS: 'SET_SUCCESS',
}

export const productsMutations = {
  SET_TOTAL_PRODUCTS: 'SET_TOTAL_PRODUCTS',
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_SUCCESS: 'SET_TOKEN_SUCCESS',
  SET_ERROR: 'SET_TOKEN_ERROR',
  RESET_STATE: 'RESET_TOKEN_STATE',
  SET_SELECTED_PRODUCT: 'SET_SELECTED_PRODUCT',
}
